refactor(tooltip): refactoring to the new structure + tests
wc-catalogue/blaze-elements pull request #139
Opened 2017-01-25 15:39 UTC by hopkins-tk

- tooltip refactored to the new style
- tests added

2017-01-25 16:47 UTC, Hotell requested changes

2017-01-25 16:47 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +      expect( element.has('.c-tooltip') ).to.be.true;
we use just `to.equal` or `to.deep.equal` for assertions

2017-01-25 16:47 UTC, Hotell commented on packages/tooltip/Tooltip.tsx
> +      'bl-tooltip': TooltipProps & Partial<HTMLElement>,
root node is `span` so `HTMLSpanElement`

2017-01-25 16:47 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +  it( 'should render with top tooltip', () => {
this and following test are doing the same assertions. Unit test should be clean as our codebase, so extract assertion to one function helper.

also the description of `it` isn't really telling anything.

We should probably structure every test to 2 sub `describe` one for `JSX` and one for "raw" `html` custom element usage

2017-01-26 07:29 UTC, hopkins-tk commented on packages/tooltip/Tooltip.test.tsx
> +  it( 'should render with top tooltip', () => {
Good idea with the two `describe` - I was thinking how we will want to structure this.

2017-01-26 07:33 UTC, hopkins-tk commented on packages/tooltip/Tooltip.test.tsx
> +      expect( element.has('.c-tooltip') ).to.be.true;
Great :) we have been discussing this yesterday with @elmariofredo  & @davidrus so we can take the opportunity and agree what should be the preferred version.

2017-01-26 07:47 UTC, hopkins-tk commented on packages/tooltip/Tooltip.tsx
> +      'bl-tooltip': TooltipProps & Partial<HTMLElement>,
So any other component, that has DIV as a root element should have `HTMLDivElement`?
- is this really correct?
- if we don't pass any attributes to the root element

2017-01-26 08:38 UTC, Hotell commented on packages/tooltip/Tooltip.tsx
> +      'bl-tooltip': TooltipProps & Partial<HTMLElement>,
ok it was late and I was tired :D so nevermind. Let's stick with `HTMLElement` for all intrinsic elements

2017-01-26 09:33 UTC, Hotell requested changes

2017-01-26 09:33 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +import {WrappedNode} from "bore";
pls merge with `bore` imports Webstorm has it and VSCode as well

2017-01-26 09:33 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +        <bl-tooltip label="hello" type="top"></bl-tooltip>
just a reminder how JSX works ( with bore `h` ):
` <Tooltip label="hello" type="top" />` transforms to:
- `h( Tooltip, {label:'hello', type:'top'} )` 
- which is created by `new Tooltip()`

`<bl-tooltip label="hello" type="top"></bl-tooltip>` transforms to:
- `h('bl-tooltip',{label:'hello', type:'top'})`
- which is created by `document.createElement`

2017-01-27 15:34 UTC, Hotell requested changes
just minor tweaks. Otherwise LGMT. and lets wait for new bore release. Good job @hopkins-tk !

2017-01-27 15:34 UTC, Hotell commented on packages/tooltip/Tooltip.tsx
> +type TooltipTypesType = keyof typeof TooltipTypes;
we dont need that suffix `Typ` in name. We now that it is a type alias already ;)

2017-01-30 07:42 UTC, hopkins-tk commented
This is failing because of skatejs/bore#11

2017-01-30 08:06 UTC, Hotell commented
We should temporarely monkey patch bore so we don't get blocked by it

2017-01-31 14:22 UTC, hopkins-tk commented
Rebased & refactored to the newest version of tests we have agreed on.

2017-01-31 14:40 UTC, Hotell requested changes

2017-01-31 14:40 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +      it( `should render with correct label using property`, () => {
this test is doing exactly the same as last one

2017-01-31 14:40 UTC, Hotell commented on packages/tooltip/Tooltip.test.tsx
> +      it( `should render with correct label using property`, () => {
probably you wanted to us `attributes` in the first one

2017-01-31 14:40 UTC, Hotell commented on packages/tooltip/Tooltip.tsx
> +  label?: string,
label should be required

2017-01-31 15:24 UTC, Hotell approved these changes

2017-01-31 15:30 UTC, merged