Test sg with btn
wc-catalogue/blaze-elements pull request #143
Opened 2017-01-27 12:36 UTC by Hotell

2017-01-27 12:40 UTC, Hotell commented
this is failing because of https://github.com/skatejs/bore/issues/11

2017-01-27 13:54 UTC, devopsmariocom requested changes

2017-01-27 13:54 UTC, elmariofredo commented on docs/styleguides/TESTING.md
> +        return mount( `<bl-button>huhuhu</bl-button>` )
can we use some simple helper which we cane safely remove after skatejs/bore#11 is fixed?

2017-01-27 13:54 UTC, elmariofredo commented on docs/styleguides/TESTING.md
> +2. API - primarily props. attributes if we support it. ( if we use attributes reflection jsut test string html version for that API)
typo `jsut` ☂️

2017-01-27 13:54 UTC, elmariofredo commented on docs/styleguides/TESTING.md
> +    it( `should render `, () => {
extra space or sentence is not finished 🐇

2017-01-27 13:54 UTC, elmariofredo commented on wct.conf.js
> +  extraScripts: [
is this necessary? if so can you please explain in comment 💂

2017-01-27 14:07 UTC, Hotell commented on wct.conf.js
> +  extraScripts: [
forgot to remove, thx

2017-01-27 15:36 UTC, Hotell commented on docs/styleguides/TESTING.md
> +        return mount( `<bl-button>huhuhu</bl-button>` )
right, good idea. Will do. others PR can benefit from it as well

2017-01-30 07:39 UTC, hopkins-tk requested changes

2017-01-30 07:39 UTC, hopkins-tk commented on packages/button/Button.test.tsx
> +  it( `should render via JSX IntrinsicElement `, () => {
Space at the end.

2017-01-30 07:39 UTC, hopkins-tk commented on packages/button/Button.test.tsx
> +  it( `should render `, () => {
Space at the end.

2017-01-30 12:57 UTC, devopsmariocom approved these changes

2017-01-30 13:00 UTC, davidrus approved these changes
"Pome do toho!!!"

2017-01-30 13:21 UTC, Hotell commented
can you pls re-review @hopkins-tk ASAP ? thx

2017-01-30 13:38 UTC, hopkins-tk approved these changes

2017-01-30 13:42 UTC, merged