refactor(calendar): init component logic & repair range fn & tests
wc-catalogue/blaze-elements pull request #156
Opened 2017-02-03 11:35 UTC by davidrus

affects: bl-calendar

Some notes:
- month and year must be defined in `prop()` because we need to rerender after any change
  - I tried to use `props(...)`, but I don't wanna have year and month in type `Props` because I can't have public interface for setting this 
- I replaced setter of `selectedDate` to use `props(...)`
- new tests including test of i18n

2017-02-03 12:01 UTC, davidrus commented
Rebased

2017-02-07 14:01 UTC, davidrus commented
Ready to review @Hotell

2017-02-07 15:18 UTC, Hotell requested changes
Good job overall ! just few tweaks

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/Calendar.test.tsx
> +import { Calendar } from './';
we have to import explicitly from './index' , because some issues with build....

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/Calendar.test.tsx
> +        const handleChange = ( e: CustomEvent ) => {
nit pick. use our customChangeEvent type

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/Calendar.tsx
>    static range( n: Number ) {
we should use `number` === primitives `Number` is object

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/index.demo.tsx
> +import { CustomChangeEvent } from '../_helpers/definitions/events';
import only from "barel", always double check what Webstorm did to you! 🗡 :D

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/Calendar.tsx
> +    let currentDate = startOfWeek( date,
let's talk about this and the following double forEach

2017-02-07 15:18 UTC, Hotell commented on packages/calendar/Calendar.tsx
> +    return Array.from( { length: n } as any, ( value: number, key: number ) => key );
hmm what is this doing?

2017-02-07 21:00 UTC, Hotell approved these changes

2017-02-07 21:01 UTC, merged