chore(generate-configs): prevent dependencies override
wc-catalogue/blaze-elements pull request #187
Opened 2017-02-12 16:33 UTC by elmariofredo

2017-02-12 16:38 UTC, elmariofredo commented
Closing #180

2017-02-12 21:06 UTC, Hotell requested changes
overall good job! 
just few nit picks about naming, simplifying and structuring code base.

in the future we should provide also tests for this

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  fs.writeFileSync(path.resolve(packageRootDir, 'tsconfig.json'), JSON.stringify(tsconfigJsonTemplate, null, 2) + "\n")
instead of using comments, a function with appropriate name could have been superior ;)

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  fs.writeFileSync(path.resolve(packageRootDir, 'tsconfig.json'), JSON.stringify(tsconfigJsonTemplate, null, 2) + "\n")
everytime you concat strings with `+` a kitten dies :D

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +
this `for loop` feels like it's 1996 again :P

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  // Generate package.json file base on package package.json file and template
package package packaaaage, omelet du fromaaaaz :D sorry, can we rename it somehow ? thx

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  const originalPackageJson = (
there is no need for parenthesis. We write ternary on new lines
```
const originalPackageJson = fs.existsSync( packagePackageJsonPath ) 
  ? require( packagePackageJsonPath ) 
  : {}
```

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +    dependencies: originalPackageJson.dependencies || undefined
this is not necessary, if dependencies don't exist it will be `undefined` by default

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  fs.writeFileSync( path.resolve(packageRootDir, 'package.json'), packageJsonString );
next time maybe use just `resolve` without "long" object path chaining

```js
const {resolve} = require('path');

// .... 
```

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> +  fs.writeFileSync( path.resolve(packageRootDir, 'package.json'), packageJsonString );
there is `'package.json'` string used at least 3 times ( also tsconfig ). Maybe rather assign it to variable and use that variable ( DRY, Refactoring friendly )

2017-02-12 21:06 UTC, Hotell commented on toolbelt/generate-configs.js
> -    name: `@blaze-elements/${packageName}`,
*suggestion* => we can maybe use power of desctructuring here:

```js
const {
  name=`@blaze-elements/${packageName}`,
  version='1.0.0',
  dependencies
} = fs.existsSync( packagePackageJsonPath ) 
  ? require( packagePackageJsonPath ) 
  : {}

const packageJson = {
 ...{name, version, dependencies}
};

savePackageConfigTo(packageRootDir, {name:packageName, config:packageJson});


function savePackageConfigTo(where,{name,config}={}){
  const configToWrite = serializeConfig(config).replace(/packageName/g, name);
  fs.writeFileSync( path.resolve(where, 'package.json'), configToWrite );
}

function serializeConfig( config ){
 return `${JSON.stringify( config, null, 2)}\n`;
}
```

2017-02-12 21:40 UTC, closed without merging

2017-02-13 03:01 UTC, Hotell commented
Interesting why did you just "closed"  this without further ado?