fix(tag): fix tag selector import
wc-catalogue/blaze-elements pull request #189
Opened 2017-02-13 13:07 UTC by hopkins-tk

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/wc-catalogue/blaze-elements/issues/178

**What is the new behavior?**
**TagSelector** import is added 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-02-13 13:10 UTC, hopkins-tk commented
Fixes #178

2017-02-13 14:14 UTC, Hotell requested changes

2017-02-13 14:14 UTC, Hotell commented on packages/tag/index.ts
> +import './TagSelector';
both need to be imported:

```
import './Tag';
import './TagSelector';
```

 in next PR whole structure should be refactored to common pattern

See https://github.com/wc-catalogue/blaze-elements/issues/191

2017-02-14 21:17 UTC, Hotell approved these changes

2017-02-15 08:39 UTC, merged