WIP: feat(select): add Select and Option component
wc-catalogue/blaze-elements pull request #221
Opened 2017-02-22 14:01 UTC by davidrus

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
`<select>` element does not have blaze wc component

**What is the new behavior?**
- `<select>` has `<bl-select>` as blaze wc component
- `<option>` has `<bl-option>` as blaze wc component

**Example**
`
<bl-select value="en">
  <bl-option value="cs">Cesky<bl-option>
  <bl-option value="en">English<bl-option>
</bl-select>
`
- English is highlighted as selected
- Value of bl-select is actual selected option

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-02-22 21:25 UTC, Hotell requested changes
Overall looking good, just few tweaks needed. thx

2017-02-22 21:25 UTC, Hotell commented on packages/select/Option.tsx
> +};
these kind of commits has to use `style` instead of `chore`. It's just nit pick, I know, but we wanna stick to and follow our guidelines :)

if you tslint fix/ run formatter just for one package `style(package-name): apply formatter, fix lint errors`, if it's touching multiple packages just `style: apply formatter`

2017-02-22 21:25 UTC, Hotell commented on packages/select/Option.tsx
> +import { GenericEvents } from '../_helpers/index';
multiple imports from `helpers` internals, pls move everything to import from one entry point ( `helpers` )

2017-02-22 21:25 UTC, Hotell commented on packages/select/Option.tsx
> +@customElement( 'bl-option' )
As I showed you during grooming session, we register elements to customElements container solely in barrel file. Pls see `button` for reference

2017-02-22 21:25 UTC, Hotell commented on packages/select/Option.tsx
> +  @prop( { type: Boolean } ) _selected = false;
underscores for class properties are used only if you create getter/setter to that property ( which you do )
pls explicitly use private `@prop( { type: Boolean } ) private _selected: false`,

2017-02-22 21:25 UTC, Hotell commented on packages/select/Option.tsx
> +    return <SelectCardItem selected={this.selected}>
use parenthesis and move code to new line
```
return (
   <SelectCardItem>.....</>
)
```

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +import { GenericEvents, prop } from '../_helpers';
multiple helpers import again from private api

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +import Option from './Option';
pls adhere to proper imports order
- 3rd party / node modules first
- other package import seconds
- internal imports last

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +@customElement( 'bl-select' )
again pls see button, how we register custom elements to container

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +  @prop( { type: String } ) placeholder: string;
this needst to be `attribute: { source: true } ` as well

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +  @prop( { attribute: true } ) value: any;
do we really need 2 way reflection to attributes? what if value is object or so?

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +  get selectedViewValue(): string {
this is passing TSC? because it returns string or void, we should be consistent

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +      this.open && <SelectCard>
2 times open condition and parenthesis missing.

consider:

```ts
this.open && ...[
  <SelectCard>
     <slot ref={this.setSlot} slot="body" />
  </SelectCard>,
  <SelectOverlay onClick={this.toggleOptions} isFullpage isTransparent />
]
```

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +    this.open = !this.open;
we dont directly set props, use `props` function

2017-02-22 21:25 UTC, Hotell commented on packages/select/components/Button.tsx
> +import Button from '../../button/Button';
`import Button from @baze-elements/button/Button`

2017-02-22 21:25 UTC, Hotell commented on packages/select/components/Card.tsx
> +import { Card } from '../../card/Card';
`import Card from @baze-elements/card/Card`

2017-02-22 21:25 UTC, Hotell commented on packages/select/components/CardItem.tsx
> +import { CardItem } from '../../card/CardItem';
`import CardItem from @baze-elements/card/CardItem`

2017-02-22 21:25 UTC, Hotell commented on packages/select/components/Overlay.tsx
> +import { Overlay } from '../../overlay/Overlay';
`import Overlay from @blaze-elements/overlay/Overlay`

2017-02-22 21:25 UTC, Hotell commented on packages/select/index.demo.tsx
> +import Select from './Select';
once you register them correctly you will need to import from index
`import {Select,Options} from './index'`

2017-02-22 21:25 UTC, Hotell commented on packages/select/index.test.ts
> +import './Button.test';
uh? what is this?

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +  attributeChangedCallback() {
whoa this is wrong, I guess you miss typed the life cycle hook? 
it should be`connectedCallback`

**NOTE**
 --> we never use `attributeChangedCallback` if we need custom watch for props we use `updatedCallback`

2017-02-22 21:25 UTC, Hotell commented on packages/select/Select.tsx
> +      this.open = false;
rather use one method for updating `open`. leverage `toggleOpen` or rename that function to `setOpenTo(value)`

2017-02-23 09:30 UTC, davidrus commented on packages/select/Select.tsx
> +import Option from './Option';
I have some problems with Option import from ./index, I will talk to you later...

2017-02-23 09:31 UTC, davidrus commented on packages/select/Select.tsx
> +  @prop( { attribute: true } ) value: any;
Thats true...

2017-02-23 09:33 UTC, davidrus commented on packages/select/Select.tsx
> +  get selectedViewValue(): string {
Yeah, but it shouldn't... :/

2017-02-23 11:26 UTC, davidrus commented on packages/select/components/Button.tsx
> +import Button from '../../button/Button';
I cannot do this before publishing helpers as module, because:
`Error:(9, 8) TS2307:Cannot find module '../_helpers'.` in Button.tsx 👎

2017-02-23 11:27 UTC, davidrus commented on packages/select/components/Button.tsx
> +import Button from '../../button/Button';
I keep TODO note here, and when we finish and publish helpers, we must refactor all packages where we using it.

2017-02-23 11:28 UTC, davidrus commented on packages/select/components/Card.tsx
> +import { Card } from '../../card/Card';
Same as button

2017-02-23 11:28 UTC, davidrus commented on packages/select/components/CardItem.tsx
> +import { CardItem } from '../../card/CardItem';
Same as button

2017-02-23 11:28 UTC, davidrus commented on packages/select/components/Overlay.tsx
> +import { Overlay } from '../../overlay/Overlay';
Same as button

2017-02-23 11:29 UTC, davidrus commented on packages/select/index.test.ts
> +import './Button.test';
emmm... Just test for you as reviewer :D

2017-02-23 11:49 UTC, Hotell commented on packages/select/components/Button.tsx
> +import Button from '../../button/Button';
yup, but in the meantime pls apply what works => ( button )

2017-02-23 16:19 UTC, Hotell approved these changes

2017-02-23 16:20 UTC, davidrus commented
Thank You @Hotell for your time & gr8 review 🚶

2017-02-23 16:21 UTC, merged