WIP feat(common): create from _helpers
wc-catalogue/blaze-elements pull request #223
Opened 2017-02-22 21:21 UTC by elmariofredo

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [ ] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
- _helpers is simple folder
- packages are using relative paths for other packages

**What is the new behavior?**
- _helpers are now common package
- packages are linked using proper dependecies

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-02-22 21:31 UTC, Hotell commented
readability nitpick, the title is "incomplete"

consider `feat(common): create regular package from _helpers`.

Also pls always provide links to existing issue, instead of writting by hand **What is the current behavior** section

2017-02-26 15:09 UTC, elmariofredo commented
@Hotell tests are failing for unknown reason on CI, please meanwhile try go thru my changes.

Thanks

2017-02-28 15:14 UTC, Hotell reviewed
pls do not merge. Tests are failing and there are some TS errors after our paired Code Review

2017-02-28 15:14 UTC, Hotell commented on packages/blaze-elements/index.demo.tsx
> +import '@blaze-elements/common/index.demo';
aha!

2017-02-28 16:26 UTC, Hotell commented
depends on https://github.com/wc-catalogue/blaze-elements/issues/230

2017-02-28 16:27 UTC, Hotell requested changes
depends on https://github.com/wc-catalogue/blaze-elements/issues/230. then merge with https://github.com/wc-catalogue/blaze-elements/pull/229

2017-03-03 14:18 UTC, Hotell approved these changes

2017-03-03 14:18 UTC, merged