WIP: refactor(card): follow actual guidelines && condition for rendering h...
wc-catalogue/blaze-elements pull request #233
Opened 2017-03-03 12:18 UTC by davidrus

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
We render all (Header & Footer) when is empty

**What is the new behavior?**
- `<CardHeader>` & `<CardFooter>` & `<CardContent>` added

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
*old version:*
```
<bl-card>
  <span slot="header">Header</span>
  <span slot="body">Body</span>
  <span slot="footer">Footer</span>
</bl-card>
```
*new version:*
```
<bl-card>
  <bl-card-header>Hello</bl-card-header>
  <bl-card-content>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, reiciendis.</bl-card-content>
  <bl-card-footer>Footer baby</bl-card-footer>
</Card>
```

2017-03-03 14:21 UTC, davidrus commented
Please dont look at commit message which are wrong... sorry for that :( .

2017-03-05 12:25 UTC, devopsmariocom requested changes
Jus few minor issues, but I have feeling that you will encounter few other during rebasing 😉

2017-03-05 12:25 UTC, elmariofredo commented on packages/card/Card.test.tsx
more of the question to wild, should we test that slotted elements are passed to lightDOM? I know that we should not test skatejs functionality but if someone will remove line with `<slot />` tests will pass but element will be unusable.

2017-03-05 12:25 UTC, elmariofredo commented on packages/card/Card.tsx
> +import { shadyCssStyles } from '../_helpers';
please rebase and update it to use common package as Martin did manage to merge it on Friday.

Thanks

2017-03-05 12:25 UTC, elmariofredo commented on packages/card/Card.tsx
> +export type CardProps = Props;
even that it doesn't do anything we should be probably consistent with rest of components so `Props & Events`

2017-03-06 06:15 UTC, davidrus commented on packages/card/Card.test.tsx
Finally 👍  ... that will be huuuuge rebase :) ...

2017-03-06 06:45 UTC, davidrus commented
Rebased... ufff :)

2017-03-06 06:46 UTC, davidrus commented on packages/card/Card.tsx
> +import { shadyCssStyles } from '../_helpers';
Finally 👍 ... that will be huuuuge rebase :) ...

2017-03-06 06:49 UTC, davidrus commented on packages/card/Card.test.tsx
We cant do this, because we are using polyfill in firefox and safari where slot does not exist after render :(.

2017-03-06 08:43 UTC, elmariofredo commented on packages/card/Card.test.tsx
ok let's discuss it here #238

2017-03-06 08:44 UTC, devopsmariocom approved these changes
great work but we need to wait to fix build before merging this

2017-03-06 14:13 UTC, merged