Elmariofredo/fix input dependency
wc-catalogue/blaze-elements pull request #237
Opened 2017-03-05 13:53 UTC by elmariofredo

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

Wrong version is set in tag/package.json which leads to errors on build
See #236 for details

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-03-05 14:05 UTC, Hotell approved these changes

2017-03-05 14:05 UTC, Hotell commented on packages/blaze-elements/package.json
> +    "@blaze-elements/input": "^2.0.0",
we have 2.0 input? what was the BC ?

2017-03-05 14:15 UTC, Hotell requested changes
Hmm actually. this should be possible Breaking change for blaze-elements suite, because you are introducing new BC version for input.

Use case:

As a consumer I'm using `"blaze-elements":"1.2.3"` everything works. 

Now developer has bumped one package to new version because of breaking change. If I update `blaze-elements` to `1.2.4` ( which will be published according to your commit ), my app will brake - so it should be rather `"blaze-elements":"2.0.0"` 

OR!

is Lerna smart enhough to bump `blaze-elements` to `2.0.0` ?

2017-03-05 18:33 UTC, elmariofredo commented on packages/blaze-elements/package.json
> +    "@blaze-elements/input": "^2.0.0",
I did release 2.0.1, because there was already 2.0.0 in npm, I don't see any related changes in git, so we most probably never find our.

2017-03-05 18:47 UTC, elmariofredo commented
I didn't add `BREAKING CHANGE:` as there is not really any breaking change it's just fixing bad release as someone in the past did release version input 2.0.0 for unknown reason. If you want can add it there but not sure if it's really necessary.

2017-03-06 08:54 UTC, Hotell commented on packages/blaze-elements/package.json
> +    "@blaze-elements/input": "^2.0.0",
right, so this should be a breaking change in `blaze-elements` package

2017-03-06 08:55 UTC, Hotell commented
pls let's read what I've written one more time :) I think we are not on the same page

2017-03-06 11:55 UTC, Hotell commented
as discussed on internal status meeting, we can move forward as release will be resolved within another PR. thanks @elmariofredo

2017-03-06 11:55 UTC, Hotell approved these changes

2017-03-06 12:01 UTC, merged