Introduce Link element
wc-catalogue/blaze-elements pull request #24
Opened 2016-12-20 14:36 UTC by davidrus

resolve #22

2016-12-21 15:12 UTC, hopkins-tk requested changes

2016-12-21 15:12 UTC, hopkins-tk commented on packages/link/Link.tsx
> +  target?: keyof typeof LinkTargets,
Target can be also any _frame name_ - so any string fulfilling certain criteria...

2016-12-22 11:23 UTC, davidrus commented on packages/link/Link.tsx
> +  target?: keyof typeof LinkTargets,
Thanks, thats right

2016-12-22 11:31 UTC, hopkins-tk approved these changes

2016-12-22 11:31 UTC, merged