refactor(toggle): align with current style guides
wc-catalogue/blaze-elements pull request #275
Opened 2017-03-08 13:50 UTC by elmariofredo

affects: @blaze-elements/toggle

ISSUES CLOSED: #273

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-08 14:28 UTC, hopkins-tk approved these changes

2017-03-08 14:30 UTC, hopkins-tk requested changes

2017-03-08 14:30 UTC, hopkins-tk commented on packages/toggle/Toggle.tsx
> +  } ) disabled = false;
Remove `@prop` decorator here as it is causing IE error.

2017-03-08 20:14 UTC, elmariofredo commented on packages/toggle/Toggle.tsx
> +  } ) disabled = false;
problem is that then it doesn't seems to be working, after removing @prop decorator value is not propagated from attribute to property.

2017-03-09 12:56 UTC, hopkins-tk approved these changes

2017-03-09 12:58 UTC, merged