refactor(typography): align with current style guides
wc-catalogue/blaze-elements pull request #283
Opened 2017-03-08 23:24 UTC by elmariofredo

affects: @blaze-elements/typography

Closes #263

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [x] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-08 23:25 UTC, elmariofredo commented on packages/typography/Abbreviation.tsx
> +  // FIX: enable projection from attribute
This is same issue as in https://github.com/wc-catalogue/blaze-elements/pull/275#discussion_r105011772

2017-03-09 09:28 UTC, davidrus commented
Please change issue number in commit message to #282 , current issue number is for breadcrumb :)

2017-03-09 09:30 UTC, davidrus requested changes
Good job 👍 , just change closes issue number and try prop from skate.

2017-03-09 09:30 UTC, davidrus commented on packages/typography/Abbreviation.tsx
> +  // FIX: enable projection from attribute
As we talk about this, please try use skate prop to define this property.

2017-03-09 12:23 UTC, davidrus approved these changes

2017-03-09 12:24 UTC, merged