test(collapsible): add initial test
wc-catalogue/blaze-elements pull request #45
Opened 2016-12-28 20:10 UTC by elmariofredo

2016-12-29 07:30 UTC, hopkins-tk requested changes

2016-12-29 07:30 UTC, hopkins-tk commented on wct.conf.js
> +const packages = require( './package.json' );
Name  `packages` is a bit confusing (espetialy later on the `packages.packages` part) - please consider some better name:
- package
- packageJson
- packageInfo

2016-12-30 01:58 UTC, elmariofredo commented
@hopkins-tk please review last changes, sorry had to rebase due to too many commits.

2016-12-30 07:50 UTC, hopkins-tk commented on package.json
> -    "build:publish": "npm run build && ./utils/deploy-ghpages.sh",
Won't we be missing this?
- I see the script stayed, but is nowhere used

2016-12-30 09:35 UTC, hopkins-tk commented on wct.conf.js
> +    "sauce": {
Please indent :)

2016-12-30 11:37 UTC, hopkins-tk approved these changes

2016-12-30 11:41 UTC, merged