Refactoring of typography module
wc-catalogue/blaze-elements pull request #57
Opened 2016-12-30 14:54 UTC by hopkins-tk

All typography related elements moved to single module.

2016-12-30 23:07 UTC, devopsmariocom requested changes

2016-12-30 23:07 UTC, elmariofredo commented on packages/typography/Code.scss
> +@import "../../node_modules/blaze/scss/components.typography";
please use `~` instead of `../../node_modules/`

2016-12-30 23:07 UTC, elmariofredo commented on packages/typography/index.demo.tsx
> +import { h, Component } from 'skatejs';
I guess we can remove demo files as well and put all demos directly here to shrink amount of files in this module... what do you think?

2017-01-02 09:42 UTC, hopkins-tk commented on packages/typography/index.demo.tsx
> +import { h, Component } from 'skatejs';
I have tried that at first, but it was huge file, which was not very readable, so I restored the demo files.

2017-01-02 09:52 UTC, elmariofredo commented on packages/typography/index.demo.tsx
> +import { h, Component } from 'skatejs';
yeah I meant single demo component with all examples inside, not multiple demo components within single file if that is what you mean

2017-01-02 12:17 UTC, hopkins-tk commented on packages/typography/index.demo.tsx
> +import { h, Component } from 'skatejs';
Done

2017-01-02 12:18 UTC, devopsmariocom approved these changes

2017-01-02 12:19 UTC, merged

2017-01-23 09:14 UTC, hopkins-tk commented
Closes #92