Tree WC component
wc-catalogue/blaze-elements pull request #7
Opened 2016-12-13 08:16 UTC by davidrus

This is implementation of #6

2016-12-14 11:16 UTC, devopsmariocom requested changes
I'm looking at https://beta.webcomponents.org/element/PolymerElements/paper-menu I'm not sure that their approach is good UX but what I like is more semantic way. Is there any way how to have it e.g. 

```
<Tree>
  <TreeItem>
    Directory 1
    <Tree>
      <TreeItem>File 1</TreeItem>
      <TreeItem>File 2</TreeItem>
    </Tree>
  </TreeItem>
</Tree>
```

2016-12-14 11:16 UTC, elmariofredo commented on packages/index.demo.ts
> +import './tree/Tree.demo';
please add to packages/index.ts as well

2016-12-14 11:16 UTC, elmariofredo commented on packages/tree/Tree.scss
> +  padding-left: 1em !important;
where this come from? it should be either part of global css which is currently under PR #1 at least put some comment here. thx

2016-12-14 11:16 UTC, elmariofredo commented on packages/tree/package.json
> +    "build": "../../node_modules/.bin/rimraf dist && ../../node_modules/.bin/webpack --config ../../webpack.config.js --env.element=tooltip",
please replace `tooltip` with `tree`

2016-12-14 12:10 UTC, hopkins-tk commented
I agree with @elmariofredo regarding the suggested way.

From my point of view, it would be also nicer.

Wouldn't using of 
```
<slot></slot>
```

instead of
```
<slot></slot>
{ isOpen ? <slot name="subItems" /> : null }
```

help?

2016-12-14 12:27 UTC, elemementor commented
guys I'm happy you are pushing my idea forward, as I said to @elmariofredo I'm currently busy so you are on your own.

2016-12-14 12:30 UTC, davidrus commented on packages/tree/Tree.scss
> +  padding-left: 1em !important;
I've added this, because shadow-dom does not match css selectors like ".c-tree .c-tree" which original css have [here](https://github.com/BlazeCSS/Blaze/blob/master/scss/components.trees.scss#L10) but I suggest to replace selector with class '.c-tree' what do you think? @elmariofredo

2016-12-14 12:30 UTC, davidrus commented on packages/tree/package.json
> +    "build": "../../node_modules/.bin/rimraf dist && ../../node_modules/.bin/webpack --config ../../webpack.config.js --env.element=tooltip",
Replaced

2016-12-14 12:31 UTC, davidrus commented on packages/index.demo.ts
> +import './tree/Tree.demo';
Yeah, I forgot, thanks 👍

2016-12-14 12:35 UTC, davidrus commented
@hopkins-tk we need to have condition for this slot because we are removing subitems from dom when menu is collapsed

@elmariofredo do you think that we should have someting like this? 
```
<Tree>

  <TreeSubmenu>
    <TreeItem>Directory 1</TreeItem>
    <Tree>
      <TreeItem>File 1</TreeItem>
      <TreeItem>File 2</TreeItem>
    </Tree>
  </TreeSubmenu>

  <TreeItem>File Root 1</TreeItem>

</Tree>
```

2016-12-14 12:41 UTC, elmariofredo commented on packages/tree/Tree.scss
> +  padding-left: 1em !important;
could we simply use `bl-tree` selector?

2016-12-14 12:44 UTC, davidrus commented on packages/tree/Tree.scss
> +  padding-left: 1em !important;
No, because when someone (like us in demo) use jsx instead of html web element, this selector does not match.

2016-12-14 12:53 UTC, elmariofredo commented
@davidrus well I would rather have my proposed structure. I did post link to polymer to have another opinion at the beginning of this PR so we can compare our decisions with something. For me their API is ugly and consist too much boilerplate.

I would try my proposal first and then let real world development to bring breaking changes later on. We shouldn't be afraid of doing elements even when we know that their API UX might not be perfect that's why we have each component separately and semver ;)

2016-12-14 12:56 UTC, davidrus commented
OK, I will try to do it now...

2016-12-14 13:20 UTC, davidrus commented
I removed ```hasSubItem``` flag, but have no idea how to remove ```<slot name="subItems" />``` and keep removing from DOM. 

So for now I suggest keep it as is. OK? @elmariofredo

2016-12-16 12:44 UTC, elemementor approved these changes

2016-12-16 12:46 UTC, devopsmariocom approved these changes

2016-12-16 12:46 UTC, devopsmariocom commented on packages/index.demo.ts
> +import './tree/Tree.demo';
np we should generate these files anyway ;)

2016-12-16 12:49 UTC, merged